### ISSUE TITLE
issue running zmq helloworld sample

### ISSUE THREAD

**Issue by donfanning** [chuckremes/ffi-rzmq#119]
Hello,

I'm getting the following stackdump when I run the 0MQ hello world sample.   Any ideas?

Thanks!

```
/Users/fannd009/.rvm/gems/ruby-1.9.3-p551@global/gems/ffi-1.9.8/lib/ffi_c.bundle: [BUG] Segmentation fault
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.1.0]

-- Control frame information -----------------------------------------------
c:0020 p:-17557144349994 s:0086 b:0086 l:000085 d:000085 TOP
c:0019 p:---- s:0084 b:0084 l:000083 d:000083 CFUNC  :require
c:0018 p:0157 s:0080 b:0080 l:000079 d:000079 METHOD /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54
c:0017 p:0029 s:0070 b:0070 l:000066 d:000069 BLOCK  /Users/fannd009/.rvm/gems/ruby-1.9.3-p551@global/gems/ffi-1.9.8/lib/ffi.rb:18
c:0016 p:0212 s:0067 b:0067 l:000066 d:000066 TOP    /Users/fannd009/.rvm/gems/ruby-1.9.3-p551@global/gems/ffi-1.9.8/lib/ffi.rb:3
c:0015 p:---- s:0065 b:0065 l:000064 d:000064 FINISH
c:0014 p:---- s:0063 b:0063 l:000062 d:000062 CFUNC  :require
c:0013 p:0532 s:0059 b:0059 l:000058 d:000058 METHOD /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:121
c:0012 p:0011 s:0049 b:0049 l:000048 d:000048 TOP    /Users/fannd009/.rvm/gems/ruby-1.9.3-p551/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core.rb:1
c:0011 p:---- s:0047 b:0047 l:000046 d:000046 FINISH
c:0010 p:---- s:0045 b:0045 l:000044 d:000044 CFUNC  :require
c:0009 p:0234 s:0041 b:0041 l:000040 d:000040 METHOD /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:69
c:0008 p:0021 s:0031 b:0031 l:000030 d:000030 TOP    /Users/fannd009/.rvm/gems/ruby-1.9.3-p551/gems/ffi-rzmq-2.0.4/lib/ffi-rzmq.rb:66
c:0007 p:---- s:0029 b:0029 l:000028 d:000028 FINISH
c:0006 p:---- s:0027 b:0027 l:000026 d:000026 CFUNC  :require
c:0005 p:0121 s:0023 b:0023 l:000019 d:000022 BLOCK  /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128
c:0004 p:0533 s:0020 b:0020 l:000019 d:000019 METHOD /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:39
c:0003 p:0023 s:0010 b:0010 l:0001e8 d:000558 EVAL   hello.rb:7
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0001e8 d:0001e8 TOP

-- Ruby level backtrace information ----------------------------------------
hello.rb:7:in `<main>'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `require'
/Users/fannd009/.rvm/gems/ruby-1.9.3-p551/gems/ffi-rzmq-2.0.4/lib/ffi-rzmq.rb:66:in `<top (required)>'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:69:in `require'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:69:in `require'
/Users/fannd009/.rvm/gems/ruby-1.9.3-p551/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core.rb:1:in `<top (required)>'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:121:in `require'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:121:in `require'
/Users/fannd009/.rvm/gems/ruby-1.9.3-p551@global/gems/ffi-1.9.8/lib/ffi.rb:3:in `<top (required)>'
/Users/fannd009/.rvm/gems/ruby-1.9.3-p551@global/gems/ffi-1.9.8/lib/ffi.rb:18:in `rescue in <top (required)>'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'

-- C level backtrace information -------------------------------------------

   See Crash Report log file under ~/Library/Logs/CrashReporter or
   /Library/Logs/CrashReporter, for the more detail of.

-- Other runtime information -----------------------------------------------

* Loaded script: hello.rb

* Loaded features:

    0 enumerator.so
    1 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/x86_64-darwin14.1.0/enc/encdb.bundle
    2 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/x86_64-darwin14.1.0/enc/trans/transdb.bundle
    3 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/x86_64-darwin14.1.0/rbconfig.rb
    4 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/thread.rb
    5 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/compatibility.rb
    6 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
    7 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
    8 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/errors.rb
    9 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
   10 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
   11 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
   12 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/basic_specification.rb
   13 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/stub_specification.rb
   14 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/util/stringio.rb
   15 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
   16 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
   17 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb
   18 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb
   19 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb
   20 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems.rb
   21 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
   22 /Users/fannd009/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[1]    75709 abort      ruby hello.rb
```

**Comment by donfanning** [comment]
closing as I just noticed this github is in maintenance mode and to move on..

**Comment by chuckremes** [comment]
The only idea I have is for you to upgrade MRI 1.9.3 to 2.x. The 1.9.3 series of releases were very poor and had a lot of bugs with handling C extensions (which is required for MRI FFI support). Upgrade the interpreter and try again.
