### ISSUE TITLE
rake -T  error

### ISSUE THREAD

**Issue by janckerchen** [chuckremes/ffi-rzmq#123]
I clone the repo and run " bundle exec rake -T",  show errors.

my env

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
$ brew info zmq
zeromq: stable 4.2.2 (bottled), HEAD

$ bundle
Fetching gem metadata from http://rubygems.org/........
Fetching version metadata from http://rubygems.org/.
Installing rake 12.0.0
Installing diff-lcs 1.3
Installing ffi 1.9.18 with native extensions
Installing rspec-core 2.99.2
Installing rspec-mocks 2.99.4
Using bundler 1.14.6
Installing rspec-expectations 2.99.2
Installing ffi-rzmq-core 1.0.5
Installing rspec 2.99.0
Using ffi-rzmq 2.0.4 from source at `.`
Bundle complete! 4 Gemfile dependencies, 10 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

```
error

```
jason@JsiMac /opt/dev_opensource/ffi-rzmq $ rake -T
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007ff5011ba550>
/opt/dev_opensource/ffi-rzmq/Rakefile:4:in `new'
/opt/dev_opensource/ffi-rzmq/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

with --trace

```
$ rake -T --trace
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007f92809ba608>
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:143:in `initialize'
/opt/dev_opensource/ffi-rzmq/Rakefile:4:in `new'
/opt/dev_opensource/ffi-rzmq/Rakefile:4:in `<top (required)>'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/jason/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/jason/.rbenv/versions/2.3.1/bin/rake:23:in `load'
/Users/jason/.rbenv/versions/2.3.1/bin/rake:23:in `<main>'
```

**Comment by janckerchen** [comment]
downgrade rake version can fix this.

there is no  specified version for rake  in ffi-rzmq.gemspec

```
...
  s.add_runtime_dependency "ffi-rzmq-core", [">= 1.0.1"]
  s.add_development_dependency "rspec", ["~> 2.14"]
  s.add_development_dependency "rake"
...
```

**Comment by chuckremes** [comment]
Thank you for the report. I fixed it by updating `rspec`. Will push changes today.
